### ISSUE TITLE
Maximize on restore

### ISSUE THREAD

**Issue by SegaraRai** [TheGuardianWolf/ThunderbirdTray#2] opened 2019-12-29 12:18 UTC
The window will be the normal size on restore, but can it be maximized on restore if it was maximized before hiding to tray?

**Comment by TheGuardianWolf** [comment] 2019-12-29 13:56
I'm getting the behavior that you want with my Thunderbird, are you currently using the .NET Core version or the .NET Framework?

I think the .NET Framework one works a bit better for compatibility between different systems.

**Comment by SegaraRai** [comment] 2019-12-29 14:00
I'm using .NET Core Self Contained version

**Comment by TheGuardianWolf** [comment] 2019-12-29 14:02
Would you mind trying out the .NET Framework one? I might just remove the .NET Core one and backport NET Framework to 4.5 to cover older systems.

**Comment by SegaraRai** [comment] 2019-12-29 14:07
Just tried .NET framework version, but still doesn't work.

**Comment by TheGuardianWolf** [comment] 2019-12-29 14:08
Okay, in that case, could you tell me your OS version?

I think I have a solution but I'll try to test it first.

**Comment by SegaraRai** [comment] 2019-12-29 14:11
Windows 10 Pro 1909 18363.535

**Comment by TheGuardianWolf** [comment] 2019-12-29 15:08
I'm a version behind you, I'll see what's up with the latest after I do my upgrade.

**Comment by SegaraRai** [comment] 2019-12-29 15:28
I noticed that it gets maximized when I open from pinned taskbar icon (not from task tray icon).
I'll use this method for now.

**Comment by TheGuardianWolf** [comment] 2019-12-30 04:56
Thanks for that comment, I've always opened it from the taskbar so that's why I've never found that issue. This has been fixed in the latest release, would you mind trying that one (v1.3.0)?

**Comment by SegaraRai** [comment] 2019-12-30 05:58
Worked on both .NET Framework version and .NET Core (self contained) version!
Thank you for the fix!

**Comment by WildByDesign** [comment] 2019-12-30 15:34
I'm a long time user of Thunderbird, since early Phoenix releases. I had used many of the old TB extensions to minimize to tray but those always had issues. So I was pleasantly surprised to see your program mentioned on Ghacks article. Excellent work and thank you for your time and contributions to this project.

Anyway, I just started using the latest 1.3.0 right now, particularly the ThunderbirdTray.NETFramework.zip build. I am experiencing this same issue. I have always used TB full screen so this bug is a bit of a stand out issue to me.

**Reproduce:**  It only seems to happen when TB is already running. Therefore, starting TB first and having it run full screen as per my usual, then run ThunderbirdTray.exe for my very first time (testing purposes initially) and it takes TB out of full screen.

Clearly, my best bet would be to run ThunderbirdTray.exe first (and only) and therefore let it do the execution of TB and everything is all good that way.

But since this was just early testing purposes for me, I already had TB running prior to launching ThunderbirdTray.exe which is the only scenario that seems to cause this bug.

**Comment by TheGuardianWolf** [comment] 2019-12-30 17:52
Let me have a look at this, should be an easy fix if it's just me overlooking something.

And wow, didn't know this would get into an article, this project initially was just me messing around with .NET Core.

**Comment by TheGuardianWolf** [comment] 2019-12-30 18:11
I was not able to reproduce this unfortunately, could I grab your OS version?

I might have to give you a pre-release with a logger implemented so I know what's going on behind the scenes, would you be willing to run that and paste over the log file it generates?

Lastly, does your Thunderbird produce any additional windows from add-ons when you are using it, specifically when you open this app?

**Comment by WildByDesign** [comment] 2019-12-30 23:29
@TheGuardianWolf  I am running Windows 10 (19041.1) 64-bit. Thunderbird build is 68.3.1 stable release, also 64-bit build.

Yes, I am happy to help test any debug builds with logging and such and I can share the logs with you.

I don't have any specific windows that pop up from add-ons during startup or anything like that. However, I will give you a list of my add-ons just in case it may be helpful.

CompactHeader 3.0.0beta5
Hide Local Folders 2.1
Lightning 68.3.1.1
Provider for Google Calendar 68.2.1

Thank you for your time. Cheers!

**Comment by TheGuardianWolf** [comment] 2019-12-31 08:03
No problem, I prepared this prerelease for you

https://github.com/TheGuardianWolf/ThunderbirdTray/releases/tag/v1.3.1-pre

I've implemented some logging that can be activated with ```--debug``` argument.

You can either do this yourself by creating a shortcut to the exe (use the windows shortcut wizard) or running the ```launch_debug.bat``` file if you put it in the same place as the exe.

The launch command is ```ThunderbirdTray.exe --debug```.

Unfortunately I'm not currently in a position to run a Windows preview, so hopefully logging will tell me how to fix the issue.

**Comment by WildByDesign** [comment] 2019-12-31 14:12
@TheGuardianWolf  Thank you for the additional logging capabilities. I'm running and testing in debug mode and still collecting logs. However, I'm trying various things first and then I will create separate logs each with specific actions so that it is less chaotic for you to narrow down.

One interesting thing that I noticed: This bug only happens when restoring TB from the tray icon itself. If I use the Windows task bar to restore TB, the bug does not occur. So this narrows it down slightly more from my testing yesterday. Also, TB must already be minimized.

Updated steps to reproduce:

1 - ensure TB is already running prior to running ThunderbirdTray
2 - ensure that TB is already minimized in task bar
3 - launch ThunderbirdTray
4 - click on ThunderbirdTray in system tray (TB restores but not full screen)

If we did these exact same steps, but changed step 4 to clicking on TB from task bar instead of clicking on ThunderbirdTray in system tray, TB restores properly to full screen.

I should also note specifically that this issue only occurs once. So this would only happen once per day if you left TB running all day, or once per session depending on how often you start TB. Therefore it only seems to happen after the initial execution.

EDIT: I should correct myself on this paragraph above, it is based on execution of ThunderbirdTray not Thunderbird itself as my paragraph initially implies. You can keep TB running all day long, for example. But if you start ThunderbirdTray 5x throughout the day (hypothetically), the issue would happen five times.

Anyway, I will provide some debug logs in the next few hours after some more testing.

**Comment by WildByDesign** [comment] 2019-12-31 14:29
I've got some initial logs now to provide. I may try some additional steps and logs later in the day if I get some free time.

With both of these logs, TB is already running and is minimized on the task bar. I proceed to execute ThunderbirdTray with the debug flag. The only difference here between the two logs is that in one, I restore TB from task bar which does not reproduce the bug, and in the other log I restore TB from ThunderbirdTray system tray icon.

[TB-minimized-restore-systray.txt](https://github.com/TheGuardianWolf/ThunderbirdTray/files/4012850/TB-minimized-restore-systray.txt)
[TB-minimized-restore-taskbar.txt](https://github.com/TheGuardianWolf/ThunderbirdTray/files/4012851/TB-minimized-restore-taskbar.txt)

There seems to be some other issues after closing out of ThunderbirdTray, but with TB still running. The issues seem specific to the task bar. ThunderbirdTray is no longer running since I closed it but I kept TB running. You can restore it from task bar, but no longer can minimize it to task bar using the TB shortcut on the task bar itself. But this is separate bug and I will have to dig into this more later and, if necessary, file a separate bug report later.

Anyway, I appreciate your time and for sharing this great project with the TB community. This is quite an exciting project and, in my opinion, a very important feature that TB really should have. Cheers! And Happy New Year!

**Comment by TheGuardianWolf** [comment] 2019-12-31 15:27
Happy New Years!

Thanks for collecting the logs, I know what the first issue is actually and you are right, it'd only ever happen once after you launch the app.

With the bugfixes I did for SegaraRai, what I did was save the state of the window when the minimise event is detected. That way, when you click on the tray again, you're back to how you were before.

What I didn't think about, and is occuring - during startup, I do an initial save of the window state so that it is known. If it is already minimised, the state will be saved as "minimised" so it will then show from minimised. But from then on, this would never happen again as the state is only saved before the minimise action.

When you click the taskbar icon however, Windows is the one doing the restoring, which overrides my behavior.

I'll implement the fix for this first before I address your other issue, I already found a solution.

**Comment by TheGuardianWolf** [comment] 2019-12-31 16:31
I've updated https://github.com/TheGuardianWolf/ThunderbirdTray/releases/tag/v1.3.1-pre

Would you be able to try this again?

If you have a way to reproduce the other issue you described, I'd gladly take a look at that as well.

**Comment by WildByDesign** [comment] 2019-12-31 17:38
@TheGuardianWolf  Thank you for this fix. You were fast to implement the logging/debug and fast to implement the fix.

I can confirm that this issue that I experienced is fixed now and working great. I've tried many times to reproduce and all is well. Thank you. This issue can be closed now.

The secondary issue regarding task bar issues with TB after ThunderbirdTray has been closed is a very minor glitch but certainly not urgent. So I believe that this current issue (#2) can be closed and I will open a separate issue for the task bar issue later today or tomorrow.

**Closed as completed** 2019-12-31 23:53 UTC
Labels: bug
