### ISSUE TITLE
ThunderBirdTray cannot find the main window when used with a Chinese version of Thunderbird

### ISSUE THREAD

**Issue by cailei77** [TheGuardianWolf/ThunderbirdTray#19] opened 2020-04-22 12:08 UTC
I use the ThunderbirdTray with a Chinese version of Thunderbird, but it doesn't work all the times. I found that it did not work when the title of the main window of Thunderbird contained Chinese characters while it worked well when the title consisted of pure ASCII chars. After debugging the source, the problem was found on the capacity of windowTextBuilder in the lambda expression in the call of the EnumWindows function. I guess that StringBuilder counts the capacity by 1-byte char so that a chinese character is counted as 2 while GetWindowTextLength treats it as 1 character. So windowTextBuilder with capacity of length + 1 is always not long enough to save the title containing Chinese characters. The new program I compiled myself with  length + 5 instead works well now.

**Comment by TheGuardianWolf** [comment] 2020-04-24 11:00
First of all, thanks for doing most of the debugging for me, that really saves me a lot of time investigating the cause of the issue.

For the sake of correctness, do you know the length required as a formula? Does +5 always work? I can put this bugfix together with the next update.

Alternatively I could just switch everything over to unicode, which might solve this issue. There is another bug I am afraid of but I'll deal with it if it does happen.

**Comment by TheGuardianWolf** [comment] 2020-04-25 01:40
I released 1.5.0 with the change, could you test that out?

**Comment by TheGuardianWolf** [comment] 2020-04-26 16:16
I briefly switched to Chinese (Simplified) locale and it seems to be functional, I'll close this for now. Please re-open if needed.

**Closed as completed by TheGuardianWolf** 2020-04-26 16:16 UTC
Labels: bug
